### ISSUE TITLE
Make conversion to cm in LoadPos() more robust

### ISSUE THREAD

**Issue by mvdm** [vandermeerlab/vandermeerlab#24]
LoadPos() has a cfg option to convert pixels to cm, but this is currently done in a way that depends on the actual tracking data:

```
X_pixelsize = max(pos_tsd.data(1,:)) - min(pos_tsd.data(1,:));
Y_pixelsize = max(pos_tsd.data(2,:)) - min(pos_tsd.data(2,:));
```

This is problematic because then if the rat leans over the track more or less, or there is some errant point being picked up off the track, the result would be different even though obviously the track size didn't change!

Ideas, @aacarey? One simple way is to get the conversion factor manually once, store it in the expkeys, and give it to LoadPos as a config field.

**Comment by aacarey** [comment]
I think the best thing to do can't really be done with data that has been collected already. Ideally, an experimenter would trace the outline of the track using an LED pointed at the camera, then we can convert the units more accurately. 
Otherwise we can do as you say and get the conversion factor manually, which I think would involve estimating the true dimensions of the track based on position data (like where the rat's trajectories seem to be concentrated, rather than the breadth of the data as it spans the axes).
